### ISSUE TITLE
Error: InvalidAccessKeyId

### ISSUE THREAD

**Issue by ahmedali5530** [BetaHuhn/do-spaces-action#425]
**🐞 Describe the bug**

I am trying to upload a artifact to spaces, its actually a react app build.

**📚 To Reproduce**

```
- name: upload to spaces cdn
  uses: BetaHuhn/do-spaces-action@v2
  with:
      access_key: ${{ secrets.AWS_ACCESS }}
      secret_key: ${{ secrets.AWS_KEY }}
      space_name: ${{ secrets.AWS_BUCKET }}
      space_region: ${{ secrets.AWS_REGION }}
      source: build-files
      out_dir: test
```
"build-files" is the artifact directory 

**💡 Expected behavior**

It should work because i am providing all credentials

**🖼️ Screenshots**
![image](https://user-images.githubusercontent.com/4495669/158110806-29375000-cdfc-4a97-8a27-2a4b36098a7c.png)

**⚙️ Environment**
 - OS: [e.g. Ubuntu 18.04]
 - Action version: [e.g. v1.0.0]

**📋 Additional context**
