### ISSUE TITLE
Inaccessible host error from underlying AWS SDK library

### ISSUE THREAD

**Issue by niklilland** [BetaHuhn/do-spaces-action#493]
**🐞 Describe the bug**

When using the action as described in the docs with the property Digital Ocean tokens, we are getting the following error:
```
  with:
    access_key: ***
    secret_key: ***
    space_name: ***
    space_region: ***
    source: storybook_build
Error: UnknownEndpoint: Inaccessible host: `***.***.digitaloceanspaces.com' at port `undefined'. This service may not be available in the `us-east-1' region.
Error: Inaccessible host: `***.***.digitaloceanspaces.com' at port `undefined'. This service may not be available in the `us-east-1' region.
```

Looking at the source code for this action, it's seems like this is an error bubbling up from the underlying aws-sdk library. 

Can you provide any guidance for this? We've confirmed our secrets are correctly being loaded into our Github Action.

**📚 To Reproduce**

Set up a Digital Ocean Space per the Readme for this action. Go to deploy new data to the DO Space, and you should get this error. 

**💡 Expected behavior**

Our updated build should be deployed to our Digital Ocean Space.

**🖼️ Screenshots**

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/15895101/169118118-3e40fb0d-1a2c-4158-9f67-391e802423ac.png">

Here is our Github Workflow:
```
name: Deploy Storybook
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run:  NODE_ENV=production yarn exec nx run storybook:build-storybook --outputPath=storybook_build
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_SPACES_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACES_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACES_REGION_NAME }}
          source: storybook_build
```

**⚙️ Environment**
 - OS: tried on ubuntu-20.04 and ubuntu-latest (22.04)
 - Action version: tried with @v2 and v2.0.43

**📋 Additional context**

This doesn't seem to be a problem on another repository that is using the same action. We tried different versions of ubuntu and the action to see if it was a caching issue, but it did not seem to resolve the issue. Any help that you can provide with this issue would be really appreciated!

Note, we have also confirmed that our Github secrets are being loaded into the action's environment and are correct.
