### ISSUE TITLE
'Node12' and 'set-output' Deprecation warning

### ISSUE THREAD

**Issue by ArthurYdalgo** [BetaHuhn/do-spaces-action#623]
**🐞 Describe the bug**
![image](https://user-images.githubusercontent.com/25585428/197877317-d8d4c3a2-12c4-4789-972d-030468816cb5.png)

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: BetaHuhn/do-spaces-action, ...
`

`The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Apparently `set-output` is deprecated and will soon be disabled.

**📚 To Reproduce**

```
      - name: Upload plugins to DO space
        uses: BetaHuhn/do-spaces-action@v2
        env:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: '{ ... }'
          out_dir: '{ ... }'
```

**💡 Expected behavior**

No warnings
